language: node_js

node_js:
  - "10"

sudo: false

cache:
  yarn: true
  directories:
    - "node_modules"
    - "packages/client-mav/node_modules"
    - "packages/client-run/node_modules"
    - "packages/server-graphql/node_modules"

branches:
  only:
    - master

install:
  - cd packages/client-mav && npm ci

script:
  - npm run build:mav-demo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local-dir: packages/client-mav/dist/client-mav
  on:
    branch: master
